spring:
  datasource-data:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:~/berry_comment
    username: sa
    password: ""

  datasource-meta:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:~/berry_comment_meta
    username: sa
    password: ""

  #배치 자동 실행 방지
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-@@platform@@.sql
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: berry_comment
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 29114570197-d3qsblq1t7du195b9dd70t3ravdtdo4e.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  issuer: wjdehdwn2475@naver.com
  secret-key: tG8+zV37J3xxVvlXmNzRt3N5Cvrl9KQsnb6RXlOVHzg=

password:
  secret-key: k9hRZxvPLu+DMIjFnZ4ynQeFYVG9ZDUph5ZbY3UOvAs=



#logging:
#  level:
#    org.springframework.security: DEBUG

